export type { Calendar, NewCalendar } from "#/db-schemas/calendar";
export type { CalendarAttendee, NewCalendarAttendee } from "#/db-schemas/attendee";
export type { CalendarEvent, NewCalendarEvent, EventRecurrenceRow } from "#/db-schemas/event";
export type { CalendarReminder, NewCalendarReminder } from "#/db-schemas/reminder";
export type {
  AttendeeEventMap,
  AttendeeInvitedEvent,
  AttendeePayload,
  AttendeeRemovedEvent,
  AttendeeUpdatedEvent,
  CalendarCreatedEvent,
  CalendarDeletedEvent,
  CalendarEventMap,
  CalendarEventPayload,
  CalendarModuleEventMap,
  CalendarUpdatedEvent,
  EventCancelledEvent,
  EventCreatedEvent,
  EventDeletedEvent,
  EventEventMap,
  EventUpdatedEvent,
  ReminderCreatedEvent,
  ReminderDeletedEvent,
  ReminderDueEvent,
  ReminderEventMap,
  ReminderPayload,
  ReminderUpdatedEvent,
} from "#/pubsub";
export { ATTENDEE_EVENTS, CALENDAR_EVENTS, EVENT_EVENTS, REMINDER_EVENTS, events } from "#/pubsub";
export type {
  AttendeeFilters,
  CalendarFilters,
  CreateAttendeeInput,
  CreateCalendarInput,
  CreateEventInput,
  CreateReminderInput,
  EventFilters,
  EventRecurrence,
  OccurrencesQuery,
  ReminderFilters,
  UpdateAttendeeInput,
  UpdateCalendarInput,
  UpdateEventInput,
  UpdateReminderInput,
} from "#/schemas";
export {
  AttendeeFiltersSchema,
  AttendeeStatusSchema,
  AttendeeTypeSchema,
  CalendarAccessSchema,
  CalendarFiltersSchema,
  CreateAttendeeSchema,
  CreateCalendarSchema,
  CreateEventSchema,
  CreateReminderSchema,
  EmailSchema,
  EventFiltersSchema,
  EventRecurrenceSchema,
  EventStatusSchema,
  HexColorSchema,
  IdSchema,
  NameSchema,
  OccurrencesQuerySchema,
  RecurrenceFrequencySchema,
  ReminderChannelSchema,
  ReminderFiltersSchema,
  ReminderIntervalSchema,
  ReminderTargetSchema,
  ReminderTypeSchema,
  ScopeTypeSchema,
  TimezoneSchema,
  UpdateAttendeeSchema,
  UpdateCalendarSchema,
  UpdateEventSchema,
  UpdateReminderSchema,
  WeekdaySchema,
  WithIdSchema,
} from "#/schemas";
export type { Occurrence } from "#/services/recurrence";
export type {
  AuditAction,
  AttendeeStatus,
  AttendeeType,
  CalendarAccess,
  EventStatus,
  RecurrenceFrequency,
  ReminderChannel,
  ReminderInterval,
  ReminderTarget,
  ReminderType,
  ScheduledJob,
  Weekday,
} from "#/utils/constants";
export {
  ATTENDEE_STATUS,
  ATTENDEE_TYPE,
  AUDIT_ACTION,
  AUDIT_ENTITY_TYPE,
  CALENDAR_ACCESS,
  DEFAULT_CALENDAR_TIMEZONE,
  EVENT_STATUS,
  RECURRENCE_FREQUENCY,
  REMINDER_CHANNEL,
  REMINDER_INTERVAL,
  REMINDER_TARGET,
  REMINDER_TYPE,
  SCHEDULED_JOBS,
  WEEKDAY,
} from "#/utils/constants";

export interface CalendarModuleConfig {
  reminderScanCron?: string;
}
