#!/usr/bin/env bun

import type { Module, PlatformInstance } from "#/server";
import type { DatabaseConfig } from "#/server/db";
import { access, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { spawn } from "bun";
import { Command } from "commander";

const program = new Command();

program.name("aspen").description("Aspen OS Platform CLI").version("0.1.0");

program
  .command("db-studio")
  .description("Launch Drizzle Kit Studio for database management")
  .requiredOption("-c, --config <path>", "Path to the Aspen config file")
  .option("-p, --port <port>", "Port for Drizzle Studio", "4983")
  .option("-h, --host <host>", "Host for Drizzle Studio", "0.0.0.0")
  .option(
    "-t, --tenant <tenantId>",
    "Tenant ID (isolated mode) — launches Studio against that tenant's database",
  )
  .action(async (options: { config: string; host: string; port: string; tenant?: string }) => {
    const platformInstance = await loadPlatform(options.config);
    const dbConfig = platformInstance.db.config;

    if (!dbConfig) {
      console.error("Error: Could not get database configuration from platform");
      await platformInstance.$cleanup().catch(() => {});
      process.exit(1);
    }

    const database = await resolveDatabase(platformInstance, dbConfig, options.tenant);

    // The platform instance holds open postgres pools which keep the event
    // loop alive. Studio runs as a separate process with its own connection,
    // so release the pools before spawning it.
    await platformInstance.$cleanup().catch(() => {});

    const configDir = await mkdtemp(join(tmpdir(), "aspen-db-studio-"));
    const configPath = join(configDir, "drizzle.config.ts");
    try {
      await writeFile(configPath, renderDrizzleConfig(dbConfig, database));
      console.log(`Launching Drizzle Studio for database "${database}"...`);
      const exitCode = await runStudio(configPath, options.host, options.port);
      process.exit(exitCode);
    } finally {
      await rm(configDir, { force: true, recursive: true });
    }
  });

program
  .command("tenants")
  .description("List all tenants (isolated mode)")
  .requiredOption("-c, --config <path>", "Path to the Aspen config file")
  .action(async (options: { config: string }) => {
    const platformInstance = await loadPlatform(options.config);

    try {
      if (!platformInstance.db.resolver) {
        console.error("Error: Tenants command is only available in isolated mode");
        process.exit(1);
      }

      const tenantIds = await platformInstance.db.resolver.list();
      console.log(`Found ${tenantIds.length} tenant(s):`);
      for (const id of tenantIds) {
        console.log(`  - ${id}`);
      }
    } finally {
      // Release postgres pools so the process exits instead of hanging.
      await platformInstance.$cleanup().catch(() => {});
    }
    process.exit(0);
  });

await program.parseAsync();

async function resolveDatabase(
  platformInstance: PlatformInstance<Module[]>,
  dbConfig: DatabaseConfig,
  tenantId: string | undefined,
): Promise<string> {
  if (tenantId === undefined) {
    return dbConfig.database;
  }
  try {
    const resolved = await platformInstance.db.resolver?.resolve(tenantId);
    if (resolved) {
      return resolved;
    }
  } catch (error) {
    console.error(
      `Warning: tenant resolver failed for "${tenantId}", falling back to naming convention (${error instanceof Error ? error.message : String(error)})`,
    );
  }
  const prefix = platformInstance.db.tenantDbPrefix;
  return prefix ? `${prefix}_${tenantId}` : tenantId;
}

/**
 * Render a dependency-free drizzle-kit config (plain object, no imports) so
 * it loads regardless of where the temp dir lives relative to node_modules.
 * Studio introspects the live database, so no schema export is needed.
 */
function renderDrizzleConfig(dbConfig: DatabaseConfig, database: string): string {
  const ssl = dbConfig.ssl ? "{ rejectUnauthorized: false }" : "false";
  return `// Generated by \`aspen db-studio\`; do not edit.
export default {
  dialect: "postgresql",
  dbCredentials: {
    database: ${JSON.stringify(database)},
    host: ${JSON.stringify(dbConfig.host)},
    password: ${JSON.stringify(dbConfig.password)},
    port: ${dbConfig.port},
    ssl: ${ssl},
    user: ${JSON.stringify(dbConfig.user)},
  },
};
`;
}

/** Spawn Drizzle Kit Studio as a child process; resolves with its exit code. */
async function runStudio(configPath: string, host: string, port: string): Promise<number> {
  const command = await resolveStudioCommand();
  console.log(`Starting Drizzle Studio on http://${host}:${port} (${command.join(" ")})`);
  const child = spawn(
    [...command, "studio", "--config", configPath, "--port", port, "--host", host],
    {
      env: { ...process.env },
      stdio: ["inherit", "inherit", "inherit"],
    },
  );

  for (const signal of ["SIGINT", "SIGTERM"] as const) {
    process.on(signal, () => {
      child.kill(signal);
    });
  }

  await child.exited;

  if (child.signalCode) {
    process.kill(process.pid, child.signalCode);
    return 1;
  }
  return child.exitCode ?? 1;
}

/**
 * Prefer a drizzle-kit installed alongside @aspen-os/platform (so Studio's
 * drizzle-orm version check resolves against the platform's own install).
 * The drizzle-kit exports map hides ./bin.cjs, so locate the file directly
 * instead of resolving the subpath. Fall back to bunx (app-local install)
 * when no alongside copy is found.
 */
function resolveStudioCommand(): Promise<string[]> {
  return findDrizzleKitBin().then((binPath) =>
    binPath ? ["bun", binPath] : ["bunx", "drizzle-kit"],
  );
}

/** Search ancestors of the CLI entrypoint and cwd for drizzle-kit's bin. */
async function findDrizzleKitBin(): Promise<string | null> {
  const roots = [dirname(fileURLToPath(import.meta.url)), process.cwd()];
  const candidates = roots.flatMap((root) => ancestorBinCandidates(root));
  const hits = await Promise.all(
    candidates.map(async (candidate) => ((await pathExists(candidate)) ? candidate : null)),
  );
  return hits.find((hit) => hit !== null) ?? null;
}

function ancestorBinCandidates(root: string): string[] {
  const candidates: string[] = [];
  let dir: string | null = root;
  while (dir !== null) {
    candidates.push(join(dir, "node_modules", "drizzle-kit", "bin.cjs"));
    const parent = dirname(dir);
    dir = parent === dir ? null : parent;
  }
  return candidates;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function loadPlatform(configPath: string): Promise<PlatformInstance<Module[]>> {
  const resolvedPath = resolve(process.cwd(), configPath);
  try {
    const mod = await import(resolvedPath);
    const platformInstance = mod.platform || mod.p || mod.pm;
    if (platformInstance) {
      return platformInstance;
    }
    console.error(`Error: No 'platform' export found in ${resolvedPath}`);
    return process.exit(1);
  } catch (error) {
    console.error(`Error: Failed to load config from ${resolvedPath}`);
    console.error(error);
    return process.exit(1);
  }
}
