import {
  productsItemStatusEnum,
  productsValuationMethodEnum,
  productsVariantBasedOnEnum,
} from "#/db-schemas/enums";

import { uuidv7 } from "@aspen-os/platform/server";
import {
  boolean,
  date,
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const productsItem = pgTable(
  "products_item",
  {
    allow_negative_stock: boolean(),
    allowance_percent: numeric({ mode: "number" }),
    auto_create_assets_on_purchase: boolean().notNull().default(false),
    auto_create_batch: boolean().notNull().default(false),
    batch_number_series: text(),
    brand_id: text(),
    clean_description: text(),
    country_of_origin: text(),
    created_at: timestamp({ withTimezone: true }).notNull().defaultNow(),
    customs_tariff_no: text(),
    default_cost_center: text(),
    default_customer_id: text(),
    default_expense_account: text(),
    default_income_account: text(),
    default_material_request_type: text(),
    default_price_list: text(),
    default_purchase_uom: text(),
    default_sales_uom: text(),
    default_supplier_id: text(),
    default_uom: text().notNull(),
    default_warehouse_id: text(),
    deferral_months: integer(),
    deferred_account: text(),
    delivered_by_supplier_drop_ship: boolean().notNull().default(false),
    description: text(),
    enable_deferred_expense: boolean().notNull().default(false),
    enable_deferred_revenue: boolean().notNull().default(false),
    end_of_life_date: date(),
    grant_commission: boolean().notNull().default(false),
    has_batch_no: boolean().notNull().default(false),
    has_expiry_date: boolean().notNull().default(false),
    has_serial_no: boolean().notNull().default(false),
    has_transactions: boolean().notNull().default(false),
    has_variants: boolean().notNull().default(false),
    hsn_sac: text(),
    id: uuidv7().primaryKey(),
    image_file_id: text(),
    include_in_manufacturing: boolean().notNull().default(false),
    inspection_required_before_delivery: boolean().notNull().default(false),
    inspection_required_before_purchase: boolean().notNull().default(false),
    is_customer_provided: boolean().notNull().default(false),
    is_disabled: boolean().notNull().default(false),
    is_fixed_asset: boolean().notNull().default(false),
    is_nil_rated_or_exempt: boolean().notNull().default(false),
    is_non_gst: boolean().notNull().default(false),
    is_purchase_item: boolean().notNull().default(true),
    is_sales_item: boolean().notNull().default(true),
    is_stock_item: boolean().notNull().default(true),
    item_code: text().notNull(),
    item_group_id: text(),
    item_name: text().notNull(),
    last_purchase_rate: numeric({ mode: "number" }),
    lead_time_days: integer(),
    manufacturer_id: text(),
    manufacturer_part_no: text(),
    max_discount_percent: numeric({ mode: "number" }),
    minimum_order_qty: numeric({ mode: "number" }),
    quality_inspection_template: text(),
    retain_sample: boolean().notNull().default(false),
    safety_stock: numeric({ mode: "number" }),
    serial_number_series: text(),
    shelf_life_days: integer(),
    standard_selling_rate: numeric({ mode: "number" }),
    status: productsItemStatusEnum().notNull().default("active"),
    tax_category: text(),
    template_item_id: text(),
    uom_restrict_override: boolean(),
    updated_at: timestamp({ withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    valuation_method: productsValuationMethodEnum(),
    variant_based_on: productsVariantBasedOnEnum(),
    variant_key: text(),
    warranty_days: integer(),
    weight_per_unit: numeric({ mode: "number" }),
    weight_uom: text(),
  },
  (table) => [
    uniqueIndex("idx_products_item_code").on(table.item_code),
    index("idx_products_item_group").on(table.item_group_id),
    index("idx_products_item_brand").on(table.brand_id),
    index("idx_products_item_status").on(table.status),
    index("idx_products_item_disabled").on(table.is_disabled),
    index("idx_products_item_template").on(table.template_item_id),
    index("idx_products_item_variant_key").on(table.variant_key),
    index("idx_products_item_name").on(table.item_name),
  ],
);

export type ProductsItem = typeof productsItem.$inferSelect;
export type NewProductsItem = typeof productsItem.$inferInsert;
