export {
  activityLog,
  attachment,
  automationRule,
  automationTriggerEnum,
  comment,
  label,
  project,
  projectMember,
  projectMemberRoleEnum,
  projectStatusEnum,
  reminder,
  reminderTypeEnum,
  savedView,
  savedViewTypeEnum,
  status,
  statusCategoryEnum,
  statusTransition,
  task,
  taskAssignee,
  taskLink,
  taskLinkTypeEnum,
  taskPriorityEnum,
  taskTables,
  taskType,
  timeEntry,
  watcher,
} from "../db-schema";

import {
  activityLog,
  attachment,
  automationRule,
  comment,
  label,
  project,
  projectMember,
  reminder,
  savedView,
  status,
  statusTransition,
  task,
  taskAssignee,
  taskLink,
  taskType,
  timeEntry,
  watcher,
} from "../db-schema";

export const control_plane_schemas = {
  label,
  project,
  projectMember,
  status,
  statusTransition,
  taskType,
} as const;

export const tenant_schemas = {
  activityLog,
  attachment,
  automationRule,
  comment,
  reminder,
  savedView,
  task,
  taskAssignee,
  taskLink,
  timeEntry,
  watcher,
} as const;
