import {
  AUDIT_ACTION,
  AUDIT_ENTITY_TYPE,
  COMPLIANCE_CATEGORY,
  OBLIGATION_FREQUENCY,
  REMINDER_CHANNEL,
  RENEWAL_FREQUENCY,
  VERIFICATION_STATUS,
} from "#/utils/constants";

import { pgEnum } from "drizzle-orm/pg-core";

export const complianceCategoryEnum = pgEnum("compliance_category", [
  COMPLIANCE_CATEGORY.TAX,
  COMPLIANCE_CATEGORY.LICENSE,
  COMPLIANCE_CATEGORY.CERTIFICATE,
  COMPLIANCE_CATEGORY.PERMIT,
  COMPLIANCE_CATEGORY.INSURANCE,
  COMPLIANCE_CATEGORY.REGULATORY,
  COMPLIANCE_CATEGORY.LEGAL,
  COMPLIANCE_CATEGORY.HR,
  COMPLIANCE_CATEGORY.SAFETY,
  COMPLIANCE_CATEGORY.ENVIRONMENTAL,
  COMPLIANCE_CATEGORY.DATA_PRIVACY,
  COMPLIANCE_CATEGORY.FINANCIAL,
  COMPLIANCE_CATEGORY.VEHICLE,
  COMPLIANCE_CATEGORY.PROPERTY,
  COMPLIANCE_CATEGORY.AUDIT,
  COMPLIANCE_CATEGORY.OTHER,
]);

export const verificationStatusEnum = pgEnum("verification_status", [
  VERIFICATION_STATUS.DRAFT,
  VERIFICATION_STATUS.SUBMITTED,
  VERIFICATION_STATUS.UNDER_REVIEW,
  VERIFICATION_STATUS.VERIFIED,
  VERIFICATION_STATUS.REJECTED,
  VERIFICATION_STATUS.EXPIRED,
  VERIFICATION_STATUS.OVERDUE,
  VERIFICATION_STATUS.RENEWED,
  VERIFICATION_STATUS.ARCHIVED,
]);

export const renewalFrequencyEnum = pgEnum("renewal_frequency", [
  RENEWAL_FREQUENCY.ONE_TIME,
  RENEWAL_FREQUENCY.MONTHLY,
  RENEWAL_FREQUENCY.QUARTERLY,
  RENEWAL_FREQUENCY.SEMI_ANNUAL,
  RENEWAL_FREQUENCY.ANNUAL,
  RENEWAL_FREQUENCY.BIENNIAL,
  RENEWAL_FREQUENCY.TRIENNIAL,
]);

export const obligationFrequencyEnum = pgEnum("obligation_frequency", [
  OBLIGATION_FREQUENCY.MONTHLY,
  OBLIGATION_FREQUENCY.QUARTERLY,
  OBLIGATION_FREQUENCY.SEMI_ANNUAL,
  OBLIGATION_FREQUENCY.ANNUAL,
  OBLIGATION_FREQUENCY.BIENNIAL,
  OBLIGATION_FREQUENCY.TRIENNIAL,
  OBLIGATION_FREQUENCY.CUSTOM,
]);

export const reminderChannelEnum = pgEnum("reminder_channel", [
  REMINDER_CHANNEL.PUBSUB,
  REMINDER_CHANNEL.EMAIL,
  REMINDER_CHANNEL.BOTH,
]);

export const auditEntityTypeEnum = pgEnum("audit_entity_type", [
  AUDIT_ENTITY_TYPE.COMPLIANCE_DOCUMENT,
  AUDIT_ENTITY_TYPE.COMPLIANCE_OBLIGATION,
  AUDIT_ENTITY_TYPE.VERIFICATION_RULE,
]);

export const auditActionEnum = pgEnum("audit_action", [
  AUDIT_ACTION.CREATED,
  AUDIT_ACTION.UPDATED,
  AUDIT_ACTION.SUBMITTED,
  AUDIT_ACTION.VERIFIED,
  AUDIT_ACTION.REJECTED,
  AUDIT_ACTION.EXPIRED,
  AUDIT_ACTION.OVERDUE,
  AUDIT_ACTION.RENEWED,
  AUDIT_ACTION.ARCHIVED,
  AUDIT_ACTION.COMPLETED,
  AUDIT_ACTION.ESCALATED,
  AUDIT_ACTION.REMINDER_SENT,
  AUDIT_ACTION.SNOOZED,
  AUDIT_ACTION.ATTACHMENT_UPLOADED,
  AUDIT_ACTION.REVIEWER_ASSIGNED,
  AUDIT_ACTION.OBLIGATION_ACTIVATED,
  AUDIT_ACTION.OBLIGATION_DEACTIVATED,
  AUDIT_ACTION.DOCUMENT_GENERATED,
]);
