import {
  healthcareCompany,
  healthcareMasterVersion,
  healthcareRecallRule,
  healthcareRole,
  healthcareTemplate,
} from "#/db-schemas/admin";
import {
  healthcareChronicLog,
  healthcareExamFinding,
  healthcareImmunization,
  healthcareRegisterEntry,
  healthcareSoapNote,
  healthcareTriageEntry,
} from "#/db-schemas/allopathy";
import {
  healthcareAppointment,
  healthcareCertificate,
  healthcareQueueToken,
  healthcareVideoSession,
} from "#/db-schemas/appointments";
import {
  healthcareAyushCaseSheet,
  healthcareDietPlan,
  healthcareRepertorization,
  healthcareTherapyPackage,
  healthcareTherapySitting,
  healthcareYogaBatch,
  healthcareYogaEnrollment,
} from "#/db-schemas/ayush";
import {
  healthcareAdvance,
  healthcareCreditDebitNote,
  healthcareInvoice,
  healthcarePackageBalance,
  healthcarePricelist,
  healthcareReceipt,
} from "#/db-schemas/billing";
import { healthcareBranch } from "#/db-schemas/branch";
import { healthcareCounter } from "#/db-schemas/counter";
import {
  healthcareChairSlot,
  healthcareDentalChart,
  healthcareDentalConsent,
  healthcareLabJob,
  healthcarePlanStage,
  healthcareQuote,
  healthcareTreatmentPlan,
} from "#/db-schemas/dental";
import {
  healthcareLabOrder,
  healthcareLabPanel,
  healthcareLabResult,
  healthcareLabSample,
  healthcareLabTest,
  healthcareQcLog,
  healthcareRadioBooking,
  healthcareRadioReport,
} from "#/db-schemas/diagnostics";
import {
  healthcareClinicOrder,
  healthcareEncounter,
  healthcareEncounterAddendum,
  healthcareEncounterDiagnosis,
  healthcareFollowUp,
  healthcarePrescription,
  healthcareVitals,
} from "#/db-schemas/encounters";
import {
  healthcareFacility,
  healthcareFacilityBlock,
  healthcareSterilizationLog,
} from "#/db-schemas/facilities";
import {
  healthcareDaycareSitting,
  healthcareDrugAdministration,
  healthcareHandover,
  healthcareIoEntry,
  healthcareNursingChecklist,
  healthcareNursingEscalation,
  healthcareNursingNote,
  healthcareNursingRiskScreen,
  healthcareNursingTask,
  healthcareNursingVitals,
  healthcarePainScore,
  healthcareTriageTag,
} from "#/db-schemas/nursing";
import {
  healthcareComplianceEvidence,
  healthcareMasterEntry,
  healthcareReportDefinition,
  healthcareSeedRun,
} from "#/db-schemas/operations";
import {
  healthcareAllergy,
  healthcareCommunication,
  healthcareConsent,
  healthcareFamilyLink,
  healthcareFlag,
  healthcareMergeRequest,
  healthcarePatient,
  healthcareRecall,
  healthcareShareSlip,
} from "#/db-schemas/patient";
import {
  healthcareGrn,
  healthcarePharmacyBatch,
  healthcarePharmacyItem,
  healthcarePharmacyReturn,
  healthcarePharmacySale,
  healthcarePurchaseInvoice,
  healthcarePurchaseOrder,
  healthcareStockTransfer,
} from "#/db-schemas/pharmacy";
import {
  healthcareLeaveBlock,
  healthcarePosting,
  healthcarePractitioner,
  healthcarePractitionerEducation,
  healthcarePractitionerFee,
  healthcarePractitionerRegistration,
  healthcarePractitionerSchedule,
} from "#/db-schemas/practitioners";
import {
  healthcareAddictionChart,
  healthcareBreakGlassLog,
  healthcareCaregiverConsent,
  healthcareControlledPrescription,
  healthcareCounsellingSession,
  healthcarePsychAssessment,
  healthcareRelapsePlan,
  healthcareRiskFlag,
  healthcareSafetyPlan,
  healthcareScaleResult,
  healthcareSideEffectCheck,
} from "#/db-schemas/psych";
import {
  healthcareBreakglassGrant,
  healthcareClinicalDocument,
  healthcareConsentGrant,
  healthcareDischargeSummary,
  healthcareMedicalAddendum,
  healthcareMedicalRegister,
  healthcareMergeLog,
  healthcareMessageLog,
  healthcareMessageOptout,
  healthcareShareLog,
} from "#/db-schemas/records";
import {
  healthcareExerciseSheet,
  healthcareOutcomeScore,
  healthcareRehabAssessment,
  healthcareRehabDischarge,
  healthcareRehabEpisode,
  healthcareRehabGoal,
  healthcareRehabSitting,
} from "#/db-schemas/rehab";
import {
  healthcareBedAssignment,
  healthcareDailyLog,
  healthcareGeriatricScore,
  healthcarePolypharmacyReview,
  healthcareResident,
  healthcareRound,
  healthcareStayCharge,
  healthcareVisitLog,
} from "#/db-schemas/residents";
import {
  healthcareDiscountRule,
  healthcarePackageDef,
  healthcareService,
  healthcareServicePrice,
} from "#/db-schemas/services";
import {
  healthcareAttendance,
  healthcareExplorerGrant,
  healthcareLeaveRequest,
  healthcareRosterEntry,
  healthcareStaff,
  healthcareStaffRole,
} from "#/db-schemas/staff";

export {
  healthcareCompany,
  healthcareMasterVersion,
  healthcareRecallRule,
  healthcareRole,
  healthcareTemplate,
} from "#/db-schemas/admin";
export {
  healthcareChronicLog,
  healthcareExamFinding,
  healthcareImmunization,
  healthcareRegisterEntry,
  healthcareSoapNote,
  healthcareTriageEntry,
} from "#/db-schemas/allopathy";
export {
  healthcareAppointment,
  healthcareCertificate,
  healthcareQueueToken,
  healthcareVideoSession,
} from "#/db-schemas/appointments";
export {
  healthcareAyushCaseSheet,
  healthcareDietPlan,
  healthcareRepertorization,
  healthcareTherapyPackage,
  healthcareTherapySitting,
  healthcareYogaBatch,
  healthcareYogaEnrollment,
} from "#/db-schemas/ayush";
export {
  healthcareAdvance,
  healthcareCreditDebitNote,
  healthcareInvoice,
  healthcarePackageBalance,
  healthcarePricelist,
  healthcareReceipt,
} from "#/db-schemas/billing";
export { healthcareBranch } from "#/db-schemas/branch";
export { healthcareCounter } from "#/db-schemas/counter";
export {
  healthcareChairSlot,
  healthcareDentalChart,
  healthcareDentalConsent,
  healthcareLabJob,
  healthcarePlanStage,
  healthcareQuote,
  healthcareTreatmentPlan,
} from "#/db-schemas/dental";
export {
  healthcareLabOrder,
  healthcareLabPanel,
  healthcareLabResult,
  healthcareLabSample,
  healthcareLabTest,
  healthcareQcLog,
  healthcareRadioBooking,
  healthcareRadioReport,
} from "#/db-schemas/diagnostics";
export {
  healthcareClinicOrder,
  healthcareEncounter,
  healthcareEncounterAddendum,
  healthcareEncounterDiagnosis,
  healthcareFollowUp,
  healthcarePrescription,
  healthcareVitals,
} from "#/db-schemas/encounters";
export {
  healthcareAppointmentStatusEnum,
  healthcareBatchStatusEnum,
  healthcareEncounterStatusEnum,
  healthcareGrnStatusEnum,
  healthcareInvoiceStatusEnum,
  healthcareLabOrderStatusEnum,
  healthcarePoStatusEnum,
  healthcareQueueTokenStatusEnum,
  healthcareRadioOrderStatusEnum,
  healthcareResidentStatusEnum,
  healthcareSaleStatusEnum,
  healthcareSittingStatusEnum,
  healthcareTaskStatusEnum,
} from "#/db-schemas/enums";
export {
  healthcareFacility,
  healthcareFacilityBlock,
  healthcareSterilizationLog,
} from "#/db-schemas/facilities";
export {
  healthcareDaycareSitting,
  healthcareDrugAdministration,
  healthcareHandover,
  healthcareIoEntry,
  healthcareNursingChecklist,
  healthcareNursingEscalation,
  healthcareNursingNote,
  healthcareNursingRiskScreen,
  healthcareNursingTask,
  healthcareNursingVitals,
  healthcarePainScore,
  healthcareTriageTag,
} from "#/db-schemas/nursing";
export {
  healthcareComplianceEvidence,
  healthcareMasterEntry,
  healthcareReportDefinition,
  healthcareSeedRun,
} from "#/db-schemas/operations";
export {
  healthcareAllergy,
  healthcareCommunication,
  healthcareConsent,
  healthcareFamilyLink,
  healthcareFlag,
  healthcareMergeRequest,
  healthcarePatient,
  healthcareRecall,
  healthcareShareSlip,
} from "#/db-schemas/patient";
export {
  healthcareGrn,
  healthcarePharmacyBatch,
  healthcarePharmacyItem,
  healthcarePharmacyReturn,
  healthcarePharmacySale,
  healthcarePurchaseInvoice,
  healthcarePurchaseOrder,
  healthcareStockTransfer,
} from "#/db-schemas/pharmacy";
export {
  healthcareLeaveBlock,
  healthcarePosting,
  healthcarePractitioner,
  healthcarePractitionerEducation,
  healthcarePractitionerFee,
  healthcarePractitionerRegistration,
  healthcarePractitionerSchedule,
} from "#/db-schemas/practitioners";
export {
  healthcareAddictionChart,
  healthcareBreakGlassLog,
  healthcareCaregiverConsent,
  healthcareControlledPrescription,
  healthcareCounsellingSession,
  healthcarePsychAssessment,
  healthcareRelapsePlan,
  healthcareRiskFlag,
  healthcareSafetyPlan,
  healthcareScaleResult,
  healthcareSideEffectCheck,
} from "#/db-schemas/psych";
export {
  healthcareBreakglassGrant,
  healthcareClinicalDocument,
  healthcareConsentGrant,
  healthcareDischargeSummary,
  healthcareMedicalAddendum,
  healthcareMedicalRegister,
  healthcareMergeLog,
  healthcareMessageLog,
  healthcareMessageOptout,
  healthcareShareLog,
} from "#/db-schemas/records";
export {
  healthcareExerciseSheet,
  healthcareOutcomeScore,
  healthcareRehabAssessment,
  healthcareRehabDischarge,
  healthcareRehabEpisode,
  healthcareRehabGoal,
  healthcareRehabSitting,
} from "#/db-schemas/rehab";
export {
  healthcareBedAssignment,
  healthcareDailyLog,
  healthcareGeriatricScore,
  healthcarePolypharmacyReview,
  healthcareResident,
  healthcareRound,
  healthcareStayCharge,
  healthcareVisitLog,
} from "#/db-schemas/residents";
export {
  healthcareDiscountRule,
  healthcarePackageDef,
  healthcareService,
  healthcareServicePrice,
} from "#/db-schemas/services";
export {
  healthcareAttendance,
  healthcareExplorerGrant,
  healthcareLeaveRequest,
  healthcareRosterEntry,
  healthcareStaff,
  healthcareStaffRole,
} from "#/db-schemas/staff";

export const healthcareTables = {
  healthcareAddictionChart,
  healthcareAdvance,
  healthcareAllergy,
  healthcareAppointment,
  healthcareAttendance,
  healthcareAyushCaseSheet,
  healthcareBedAssignment,
  healthcareBranch,
  healthcareBreakGlassLog,
  healthcareBreakglassGrant,
  healthcareCaregiverConsent,
  healthcareCertificate,
  healthcareChairSlot,
  healthcareChronicLog,
  healthcareClinicOrder,
  healthcareClinicalDocument,
  healthcareCommunication,
  healthcareCompany,
  healthcareComplianceEvidence,
  healthcareConsent,
  healthcareConsentGrant,
  healthcareControlledPrescription,
  healthcareCounsellingSession,
  healthcareCounter,
  healthcareCreditDebitNote,
  healthcareDailyLog,
  healthcareDaycareSitting,
  healthcareDentalChart,
  healthcareDentalConsent,
  healthcareDietPlan,
  healthcareDischargeSummary,
  healthcareDiscountRule,
  healthcareDrugAdministration,
  healthcareEncounter,
  healthcareEncounterAddendum,
  healthcareEncounterDiagnosis,
  healthcareExamFinding,
  healthcareExerciseSheet,
  healthcareExplorerGrant,
  healthcareFacility,
  healthcareFacilityBlock,
  healthcareFamilyLink,
  healthcareFlag,
  healthcareFollowUp,
  healthcareGeriatricScore,
  healthcareGrn,
  healthcareHandover,
  healthcareImmunization,
  healthcareInvoice,
  healthcareIoEntry,
  healthcareLabJob,
  healthcareLabOrder,
  healthcareLabPanel,
  healthcareLabResult,
  healthcareLabSample,
  healthcareLabTest,
  healthcareLeaveBlock,
  healthcareLeaveRequest,
  healthcareMasterEntry,
  healthcareMasterVersion,
  healthcareMedicalAddendum,
  healthcareMedicalRegister,
  healthcareMergeLog,
  healthcareMergeRequest,
  healthcareMessageLog,
  healthcareMessageOptout,
  healthcareNursingChecklist,
  healthcareNursingEscalation,
  healthcareNursingNote,
  healthcareNursingRiskScreen,
  healthcareNursingTask,
  healthcareNursingVitals,
  healthcareOutcomeScore,
  healthcarePackageBalance,
  healthcarePackageDef,
  healthcarePainScore,
  healthcarePatient,
  healthcarePharmacyBatch,
  healthcarePharmacyItem,
  healthcarePharmacyReturn,
  healthcarePharmacySale,
  healthcarePlanStage,
  healthcarePolypharmacyReview,
  healthcarePosting,
  healthcarePractitioner,
  healthcarePractitionerEducation,
  healthcarePractitionerFee,
  healthcarePractitionerRegistration,
  healthcarePractitionerSchedule,
  healthcarePrescription,
  healthcarePricelist,
  healthcarePsychAssessment,
  healthcarePurchaseInvoice,
  healthcarePurchaseOrder,
  healthcareQcLog,
  healthcareQueueToken,
  healthcareQuote,
  healthcareRadioBooking,
  healthcareRadioReport,
  healthcareRecall,
  healthcareRecallRule,
  healthcareReceipt,
  healthcareRegisterEntry,
  healthcareRehabAssessment,
  healthcareRehabDischarge,
  healthcareRehabEpisode,
  healthcareRehabGoal,
  healthcareRehabSitting,
  healthcareRelapsePlan,
  healthcareRepertorization,
  healthcareReportDefinition,
  healthcareResident,
  healthcareRiskFlag,
  healthcareRole,
  healthcareRosterEntry,
  healthcareRound,
  healthcareSafetyPlan,
  healthcareScaleResult,
  healthcareSeedRun,
  healthcareService,
  healthcareServicePrice,
  healthcareShareLog,
  healthcareShareSlip,
  healthcareSideEffectCheck,
  healthcareSoapNote,
  healthcareStaff,
  healthcareStaffRole,
  healthcareStayCharge,
  healthcareSterilizationLog,
  healthcareStockTransfer,
  healthcareTemplate,
  healthcareTherapyPackage,
  healthcareTherapySitting,
  healthcareTreatmentPlan,
  healthcareTriageEntry,
  healthcareTriageTag,
  healthcareVideoSession,
  healthcareVisitLog,
  healthcareVitals,
  healthcareYogaBatch,
  healthcareYogaEnrollment,
} as const;

export const control_plane_schemas = {} as const;

export const tenant_schemas = healthcareTables;
