export type {
  AddGroupMemberInput,
  AttendanceFilters,
  AttendanceRequestFilters,
  CheckinFilters,
  CompensatoryLeaveFilters,
  CreateAttendanceInput,
  CreateAttendanceRequestInput,
  CreateCheckinInput,
  CreateCompensatoryLeaveInput,
  CreateDepartmentInput,
  CreateDesignationInput,
  CreateEmployeeGradeInput,
  CreateEmployeeGroupInput,
  CreateEmployeeInput,
  CreateEmploymentTypeInput,
  CreateExitInterviewInput,
  CreateFullAndFinalInput,
  CreateHealthInsuranceInput,
  CreateHolidayInput,
  CreateHolidayListInput,
  CreateLeaveAdjustmentInput,
  CreateLeaveAllocationInput,
  CreateLeaveApplicationInput,
  CreateLeaveBlockListInput,
  CreateLeaveEncashmentInput,
  CreateLeavePeriodInput,
  CreateLeavePolicyAssignmentInput,
  CreateLeavePolicyDetailInput,
  CreateLeavePolicyInput,
  CreateLeaveTypeInput,
  CreateOnboardingInput,
  CreateOnboardingTaskInput,
  CreateOvertimeSlipInput,
  CreateOvertimeTypeInput,
  CreatePromotionInput,
  CreateSeparationInput,
  CreateSeparationTaskInput,
  CreateShiftAssignmentInput,
  CreateShiftLocationInput,
  CreateShiftRequestInput,
  CreateShiftScheduleAssignmentInput,
  CreateShiftScheduleInput,
  CreateShiftTypeInput,
  CreateSkillMapInput,
  CreateTransferInput,
  DepartmentFilters,
  EmployeeFilters,
  ExitInterviewFilters,
  FullAndFinalFilters,
  LeaveAllocationFilters,
  LeaveApplicationFilters,
  LeaveBlockListFilters,
  LeaveEncashmentFilters,
  LeavePolicyAssignmentFilters,
  OnboardingFilters,
  OvertimeSlipFilters,
  PromotionFilters,
  SeparationFilters,
  ShiftAssignmentFilters,
  ShiftRequestFilters,
  TransferFilters,
  UpdateAttendanceInput,
  UpdateAttendanceRequestInput,
  UpdateCompensatoryLeaveInput,
  UpdateDepartmentInput,
  UpdateDesignationInput,
  UpdateEmployeeGradeInput,
  UpdateEmployeeGroupInput,
  UpdateEmployeeInput,
  UpdateEmploymentTypeInput,
  UpdateExitInterviewInput,
  UpdateFullAndFinalInput,
  UpdateHealthInsuranceInput,
  UpdateHolidayInput,
  UpdateHolidayListInput,
  UpdateHrSettingsInput,
  UpdateLeaveAllocationInput,
  UpdateLeaveApplicationInput,
  UpdateLeaveBlockListInput,
  UpdateLeaveEncashmentInput,
  UpdateLeavePeriodInput,
  UpdateLeavePolicyAssignmentInput,
  UpdateLeavePolicyInput,
  UpdateLeaveTypeInput,
  UpdateOnboardingInput,
  UpdateOnboardingTaskInput,
  UpdateOvertimeSlipInput,
  UpdateOvertimeTypeInput,
  UpdatePayrollSettingsInput,
  UpdatePromotionInput,
  UpdateSeparationInput,
  UpdateSeparationTaskInput,
  UpdateShiftAssignmentInput,
  UpdateShiftLocationInput,
  UpdateShiftRequestInput,
  UpdateShiftScheduleAssignmentInput,
  UpdateShiftScheduleInput,
  UpdateShiftTypeInput,
  UpdateSkillMapInput,
  UpdateTransferInput,
} from "./schemas";
export {
  AddGroupMemberSchema,
  AttendanceFiltersSchema,
  AttendanceRequestFiltersSchema,
  CheckinFiltersSchema,
  CompensatoryLeaveFiltersSchema,
  CreateAttendanceRequestSchema,
  CreateAttendanceSchema,
  CreateCheckinSchema,
  CreateCompensatoryLeaveSchema,
  CreateDepartmentSchema,
  CreateDesignationSchema,
  CreateEmployeeGradeSchema,
  CreateEmployeeGroupSchema,
  CreateEmployeeSchema,
  CreateEmploymentTypeSchema,
  CreateExitInterviewSchema,
  CreateFullAndFinalSchema,
  CreateHealthInsuranceSchema,
  CreateHolidayListSchema,
  CreateHolidaySchema,
  CreateLeaveAdjustmentSchema,
  CreateLeaveAllocationSchema,
  CreateLeaveApplicationSchema,
  CreateLeaveBlockListSchema,
  CreateLeaveEncashmentSchema,
  CreateLeavePeriodSchema,
  CreateLeavePolicyAssignmentSchema,
  CreateLeavePolicyDetailSchema,
  CreateLeavePolicySchema,
  CreateLeaveTypeSchema,
  CreateOnboardingSchema,
  CreateOnboardingTaskSchema,
  CreateOvertimeSlipSchema,
  CreateOvertimeTypeSchema,
  CreatePromotionSchema,
  CreateSeparationSchema,
  CreateSeparationTaskSchema,
  CreateShiftAssignmentSchema,
  CreateShiftLocationSchema,
  CreateShiftRequestSchema,
  CreateShiftScheduleAssignmentSchema,
  CreateShiftScheduleSchema,
  CreateShiftTypeSchema,
  CreateSkillMapSchema,
  CreateTransferSchema,
  DepartmentFiltersSchema,
  EmployeeFiltersSchema,
  ExitInterviewFiltersSchema,
  FullAndFinalFiltersSchema,
  LeaveAllocationFiltersSchema,
  LeaveApplicationFiltersSchema,
  LeaveBlockListFiltersSchema,
  LeaveEncashmentFiltersSchema,
  LeavePolicyAssignmentFiltersSchema,
  OnboardingFiltersSchema,
  OvertimeSlipFiltersSchema,
  PromotionFiltersSchema,
  SeparationFiltersSchema,
  ShiftAssignmentFiltersSchema,
  ShiftRequestFiltersSchema,
  TransferFiltersSchema,
  UpdateAttendanceRequestSchema,
  UpdateAttendanceSchema,
  UpdateCompensatoryLeaveSchema,
  UpdateDepartmentSchema,
  UpdateDesignationSchema,
  UpdateEmployeeGradeSchema,
  UpdateEmployeeGroupSchema,
  UpdateEmployeeSchema,
  UpdateEmploymentTypeSchema,
  UpdateExitInterviewSchema,
  UpdateFullAndFinalSchema,
  UpdateHealthInsuranceSchema,
  UpdateHolidayListSchema,
  UpdateHolidaySchema,
  UpdateHrSettingsSchema,
  UpdateLeaveAllocationSchema,
  UpdateLeaveApplicationSchema,
  UpdateLeaveBlockListSchema,
  UpdateLeaveEncashmentSchema,
  UpdateLeavePeriodSchema,
  UpdateLeavePolicyAssignmentSchema,
  UpdateLeavePolicySchema,
  UpdateLeaveTypeSchema,
  UpdateOnboardingSchema,
  UpdateOnboardingTaskSchema,
  UpdateOvertimeSlipSchema,
  UpdateOvertimeTypeSchema,
  UpdatePayrollSettingsSchema,
  UpdatePromotionSchema,
  UpdateSeparationSchema,
  UpdateSeparationTaskSchema,
  UpdateShiftAssignmentSchema,
  UpdateShiftLocationSchema,
  UpdateShiftRequestSchema,
  UpdateShiftScheduleAssignmentSchema,
  UpdateShiftScheduleSchema,
  UpdateShiftTypeSchema,
  UpdateSkillMapSchema,
  UpdateTransferSchema,
} from "./schemas";

export interface AttendanceSummary {
  absent: number;
  halfDay: number;
  month: string;
  present: number;
  totalDays: number;
  workFromHome: number;
}

export interface EmployeeTreeNode {
  children: EmployeeTreeNode[];
  designation: string;
  id: string;
  image: string | null;
  name: string;
}

export interface LeaveBalance {
  allocated: number;
  carryForwarded: number;
  earned: number;
  leaveType: string;
  remaining: number;
  used: number;
}

export interface OvertimeSummary {
  holidayHours: number;
  standardHours: number;
  totalHours: number;
  weekendHours: number;
}
